version: '3.9'

services:
  mongodb:
    image: mongo:7.0
    container_name: ppsaura_mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: pps_aura
    volumes:
      - mongo_data:/data/db
    networks:
      - ppsaura_net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ppsaura_backend
    restart: always
    ports:
      - '5000:5000'
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGO_URI: mongodb://admin:password123@mongodb:27017/pps_aura?authSource=admin
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - ppsaura_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ppsaura_frontend
    restart: always
    ports:
      - '3000:3000'
    environment:
      NEXT_PUBLIC_API_URL: http://backend:5000/api/v1
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - ppsaura_net

volumes:
  mongo_data:

networks:
  ppsaura_net:
    driver: bridge
